

neigborhood_list_1 <- c("cabrera", "parque virrey", "virrey", "chico", "chapinero", 
                        "chapinero teusaquillo", "carolina", "gimnasio", "nogal", "chapinero alto", 
                        "antiguo country", "chapinero central", "rosales", "refugio", "chico oriental", 
                        "cabrera alta", "chico norte", "hayuelos", "santa barbara", "chico norte iii", 
                        "bosque caldern", "refugio chapinero", "miramonte", "pardo rubio", "rincn chic", 
                        "retiro", "chiconavarra", "chico refugio", "bosque calderon", "marly", 
                        "salle", "terrazas nogal", "rosales chapinero", "chico navarra", "chico alto", 
                        "chico norte ii", "emaus", "pedregal", "altos chico", "rincon chico", 
                        "sucre", "virrey balcones", "refugio verde", "chapinero pardo rubio", "quinta camacho", 
                        "chapinero norte", "chic", "maria cristina", "chapinero marly", "cabrera terrazas", 
                        "cedritos", "acacias", "altos cabrera", "granada chapinero", "chico occidental", 
                        "chico chapinero", "chico museo", "espartillal", "mochuelo oriental", "salle pardo rubio", 
                        "chico virrey", "chico club", "bellavista", "refugio altos retiro", "antiguo country virrey", 
                        "sierras", "rosales alto", "santa bibiana", "toscama", "almeria", 
                        "chapinero flores", "rsales", "castellana", "chic iii", "chapinero alto cerros", 
                        "chico navara", "chico norte ii sector chico lago", "sector norte", "antiguo country bellun", "cabrera refugio", 
                        "quirigua", "chico san patricio", "granada", "chico nogal", "javeriana", 
                        "colinas", "emaus rosales", "lago gaitan", "santa paula", "chico carreras", 
                        "teusaquillo", "porciuncula", "luminium", "chico iii", "lago", 
                        "chico ii", "unilago", "san patricio", "castillo chapinero", "retiro balcones", 
                        "chico malcoba", "castillo", "alhambra", "chico iii sector", "chia", 
                        "galerias", "soledad", "arista santa paula", "arboleda country", "world trade center", 
                        "parque chico", "parque", "santa fe", "cedros torres majui", "sucre chapinero", 
                        "chico norte malcobas", "gustavo restrepo", "molinos norte", "colina", "chico parque", 
                        "maria cristina chapinero", "marly chapinero", "chapinero alto patio", "cabrera chico lago", "cuarto rosales", 
                        "normandia", "chic norte", "nogal parque", "chico norte iii world trade center", "ciudad sector chapinero", 
                        "NA", "rincon chico rea", "molinos", "multicentro", "alameda", 
                        "acacias chapinero", "villa carolina", "rincn chico", "concepcin chapinero", "chico central", 
                        "refugio refugio", "infinitum", "virrey sector", "patio", "virrey antiguo country", 
                        "chapinero occidental", "sector chico norte", "quinta rosales", "chico ciudad", "chapinero alto sierras", 
                        "country", "contador", "benjamin herrera", "andes", "club nogal", 
                        "boyaca real", "emaus chapinero", "ingemar castillo", "ciudad", "chico balcones", 
                        "santa ana", "rosale", "barranquilla mercedes", "chico norte iii chico lago", "sectores", 
                        "chico alto refugio", "partamento chico", "mesa", "bosques maria", "cataluna", 
                        "chile", "alto chico norte", "rosales emaus", "inmoval", "pradera norte", 
                        "chic navarra", "chico chico lago", "balcones lindaraja", "cjapinero alto", "altos refugio", 
                        "cedro golf", "bosque pinos", "santa barbara santa barbara", "belen alameda", "chico lumina", 
                        "chico country", "cedro bolivar", "parque montanas", "polo real", "chapinero torre alta", 
                        "facatativa", "chapinero alto kandinsky", "polo club", "altos riomar", "virrey parque", 
                        "san martin", "pardo rubio chapinero", "maranta", "villa", "chico norte chico lago", 
                        "terrazas rosales", "rosales balcones", "rincon chico chapinero", "metropolis", "normandia junca", 
                        "bonito", "torre alta granada chapinero", "chico leck", "centro", "puente lago", 
                        "virrey etapa", "bolivar armenia", "rincon chico iv", "rosales parque", "luxury rosales", 
                        "retiro alto", "chic alto", "chico cabrera", "chic norte iii", "torres cadiz", 
                        "sector cabrera", "club platino chico", "lago viriv", "cabrera verde", "san luis galerias", 
                        "virrey chapinero", "boyaca", "chapinero alto seguro", "chico norte ii chico lago", "robledo medellin antioquia", 
                        "canaima paseo libertadores", "ingemar pardo rubio", "chico norte iii sector chico lago", "ciudad salitre sur oriental", "clinica nogales autonorte", 
                        "virrey iv cundinamarca", "castillo pardo rubio", "sector chico", "torre alta chapinero granada", "rosales cabrera", 
                        "chapinero alto castillo", "cabrera retiro", "sanjose bavaria", "penhouse chico", "chico norte iii sector", 
                        "seminario refugio", "antuguo country", "chico navarro", "rafael nunez", "chapinero noroccidental", 
                        "emaus quinta rosales", "santa fe rincon chico", "vizcaya chapinero", "kennedy ciudad roma", "nogales", 
                        "chicho", "chapinero centro", "puente", "bacata centro", "chico norte balcones", 
                        "bonito san patricio", "oikos chapinero", "paraiso pardo rubio", "sector", "chapinero salle", 
                        "bohemio castillo", "virrey solario", "juan xxiii chapinero", "galeria", "parque retiro", 
                        "cabrera virrey", "ciudad sector chico", "sta barbara occidental", "cabrera colombia", "chapinero ambientes airbnb", 
                        "chico colombia", "chapinero alto pardo rubio", "chapialto", "sector virrey", "cabrera chic", 
                        "santa barbara occidental", "chapinero nogal", "cabrera andino", "chico chico", "pasadena", 
                        "lago gaitan chico lago", "alcazares", "lutecia", "cabrera ciudad", "alameda san antonio verbenal", 
                        "chapinero javeriana", "rosales palomar", "calleja", "bellavista chapinero", "chcio", 
                        "salitre", "chapinero alto emaus", "emaus chapinero alto", "rosales bella", "rosales bellavista", 
                        "altos retiro", "santa paula gallon", "delicioso chapinero alto", "chapinero castillo", "santa paula norte", 
                        "jardin marly", "chic virrey", "nicolas federman", "localizacion", "santa barbara central", 
                        "gpao", "prados country", "chap alto", "talmente", "chico sector ii", 
                        "chapinero chico", "chapiero alto", "altos cabrera rosales", "altos lacabrera chi resev", "rosales bellavista alta", 
                        "horizonte", "colina sultana", "emas", "recreo frailes", "salle chapinero", 
                        "chica norte iii chapinero", "the lumina", "bosques marina", "sector chapinero", "nogal norte", 
                        "sector lago", "medellin", "santa paula nororiente", "chico rincon", "chapinero emaus", 
                        "boyac", "bella castilla", "cabrera chico", "cabrera norte", "batan", 
                        "sonora", "colombia", "chico sector", "polo", "chico resevado", 
                        "town", "antiguo country chapinero", "san nicolas", "chapinero alto chapinero", "chica norte chapinero", 
                        "virrey nororiente", "salle chapinero alto", "san marcos", "mazuren colina", "chico bonito", 
                        "bellavista noroccidental", "chico navarra nororiente", "pinar alto", "nogal rosales", "chapinero chapinero", 
                        "alaia cabrera", "modelia", "esperanza nororiental", "san carlos occidente", "belmira terrazas", 
                        "chica alto chapinero", "refugio noroccidente", "serena occidente", "san cristobal norte", "retiro chapinero", 
                        "chica chapinero", "rosales minerva", "bellisimo cabrera", "bosques bellavista", "modernos", 
                        "pontevedra noroccidente", "pontevedra", "san pedro milagros san pedro milagros municipios", "cabrera nororiente", "mar cristal sur cartagena", 
                        "rincon chico nororiente", "lantana hayuelos", "rio frio chia chia", "granada occidente", "nogal chapinero", 
                        "colina campestre", "colegio gimnasio", "bosque refugio", "nogal nororiente", "bella suiza norte", 
                        "cerezos", "floralia", "fatima", "media avda ferrocarril", "villa prado", 
                        "malibu", "ciudad montes", "villas granada", "bosques canada", "san patricio balcones", 
                        "santa ana occidental", "salitre luis mara fernn", "santa barbara alta", "santa barbara oriental", "santa brbara alta", 
                        "bosque medina", "barrancas", "lisboa", "gratamira", "bochica", 
                        "parque bella suiza", "villas andalucia", "ciudad salitre", "alameda rincon", "centro historico", 
                        "bella suiza", "villa calasanz", "villa magdala", "salitre greco", "tejar angeles sur", 
                        "alejandria corinto", "alcala", "calleja alta", "santa teresa vivaldi", "santabarbara central", 
                        "bella suiza alta", "santa teresita", "altos pradera", "belmira", "sanra barbara occidental", 
                        "margaritas", "caobos salazar", "rio negro", "nicols federmn", "octubre", 
                        "colina campestre versalles", "bosque modelia", "cortijo", "gilmar colina campestre", "niza", 
                        "ferrol", "sector cedritos", "country club", "lagartos", "san jose prado", 
                        "villas", "colina campestre monet", "granja", "kennedy", "cedros", 
                        "ciudad montes puente aranda", "san antonio", "guadual", "santa mara lago", "niza antigua", 
                        "batn", "castilla", "venecia", "bella suiza tercer", "arcadia", 
                        "pepe sierra", "icata", "santa matilde", "bosque izquierdo", "puente aranda", 
                        "galan", "banco central", "san luis", "quinta paredes", "belalcazar", 
                        "popular modelo", "armenia", "palermo", "san fernando", "angeles", 
                        "alamos norte", "danubio centauros", "santa helenita", "gilmar", "san jorge", 
                        "ciudad kennedy", "san antonio antonio narino", "villa oriental", "antonio narino", "quiroga", 
                        "fragua", "villas aranjuez", "parque santa barbara", "norte", "country calleja", 
                        "mediterraneo", "egipto", "belalcazar norte", "felicidad", "santa monica", 
                        "giralda", "san joaquin", "torreladera blanca", "ciudadela colsubsidio", "britalia", 
                        "niza norte", "santa margarita", "provenza lagos cordoba", "lagos cordoba", "techo", 
                        "villa alsacia", "velodromo medellin", "mandalay", "mandalay kennedy", "salitre occidental", 
                        "minuto dios", "real", "sabanas dorado", "bonanza", "nieves", 
                        "navarra", "altos bella suiza", "barrancas norte", "santa teresa", "orquideas", 
                        "verbenal", "dardanelo", "san antonio norte", "alameira", "modelia occidental", 
                        "julio", "san jose", "america", "salite oriental", "acevedo tejada", 
                        "alfonso lopez", "baquero", "candelaria", "cundinamarca", "veraguas", 
                        "san rafael puente aranda", "trinidad", "vision colombia", "iberia", "castellana balcones", 
                        "vergel", "agosto", "simon bolivar", "zelandia", "capri", 
                        "san miguel", "mazuren", "progreso", "yerbabuena chia", "ceiba cucuta", 
                        "terrazas", "vereda fonqueta chia", "aurora", "villa rocio mosquera", "san pablo jerico", 
                        "santa lucia", "sta barbara", "prado pinzon", "terrazas altos santa ana", "country sur", 
                        "hipotecho", "marsella lockennedy", "cedrtitos", "carabelas ciudad montes", "pradera", 
                        "santa barbara occ", "portal norte", "santa ana oriental", "santa brbara", "recodo country", 
                        "centro internacional", "carabelas", "galn", "banco central teusaquillo", "gaitan", 
                        "balzani", "santa cecilia normandia", "felicidad arboledajunto", "ciudad salitre oriental", "amricas kennedy", 
                        "hipotecho sur kennedy", "etapa", "modelo norte", "salitre aitana", "ilarco", 
                        "villa nelly iii sector kennedy", "maria kennedy", "potosi", "tisquesusa", "marly santa teresita", 
                        "sotileza", "rincon angeles", "sector noroccidente", "aranjuez", "centro palatino", 
                        "salitre ibiza iii", "torres salitre alto", "floresta", "santa isabel occidental", "garces navas" 
)

neigborhood_list_2 <- c("santa rita", "santa isabel", "vivir noroccidente", "sta bibiana", "cedritos panorama", 
                        "bella suiza alta iraka balcones", "zotileza", "nicolas fedeman", "quirinal", "chapinero occidental teusaquillo", 
                        "esmeralda", "cortijo santa barbara", "aures", "niza norte ii sector", "lagos cordoba alhambra", 
                        "villa javier", "alameda norte", "cedro narvaez", "san antonio noroccidental", "torcoroma san cristobal norte", 
                        "ingles sur", "plazuela virrey", "cali", "serena", "molinos viento", 
                        "mercedes", "britalia norte", "casablanca", "castilla real castilla", "sauzalito ciudad salitre occidente", 
                        "alejandria", "arrayanes normandia", "bosques alameda", "tarragona modelia", "jazmin puentearanda", 
                        "fraguita", "san vicente tunjuelito", "jazmin ciudad montes", "maria", "san pedro san jose bavaria", 
                        "santa helena baviera iv sector", "colina gratamira", "americas occidental ii iii", "toberin", "andes norte", 
                        "octubre villavicencio", "angeles puente aranda", "teusaquillo teusaquillo", "sector america", "parque central salitre", 
                        "soledad teusaquillo", "normandia occidental", "normandia sector", "alsacia", "atahualpa", 
                        "zarzamora", "espanola", "bosa escocia vii sector", "villas mediterraneo norte", "cantalejo", 
                        "colina campestre iii iv vi", "bosque canada", "galerias tour realidad", "bella suiza bella suiza", "alcala norte", 
                        "villa alsacia castilla", "calleja baja", "villaluz", "villas madrigal", "europa", 
                        "bosques mariana", "camelia", "ciudad sector pasadena", "julio flores", "senora paz bavaria", 
                        "santa barbara parque", "san fernando octubre", "san felipe barrios unidos", "claret quiroga", "contador ii", 
                        "san fernando occidental", "campin occidental", "salitre oriental estacion", "pio estacion banderas", "santander", 
                        "muzu", "bolivia", "belen", "americas occidental", "belarcazar", 
                        "marquez", "san vicente ferrer", "santa babara", "torre bacata", "bellasuiza", 
                        "santa babara occidental", "parque central bavaria", "aloha norte castilla", "rincon salitre", "campestre acacias meta", 
                        "vizcaya", "restrepo", "unicentro", "san felipe", "floresta norte", 
                        "lisboa cedritos", "colina campestre ii etapa", "caobos zalazar cedritos", "rafael nuez", "bosque alameda", 
                        "bonito centro golf", "san rafael", "guaca", "estrada", "chico miranda", 
                        "salitre salitre", "sante barbara", "ciudad salitre ventura", "salitre azalea", "hipotecho sur", 
                        "fiori", "alameda campestre", "llanura mayo", "usatama", "rios", 
                        "torres castilla", "heroes", "redil andalucia norte", "portales norte", "marsella", 
                        "kennedy timiza", "kennedy central", "castilla villa alsacia", "villa madrigal", "alamos", 
                        "cerros", "roble caobos salazar", "barbara central", "arrayanes sauzalito", "quinta paredes teusaquillo", 
                        "catalina ii", "santa barbara sierra", "zima", "zima martires", "milenta", 
                        "altos", "kennedy unidos", "kennedy colombiano", "kennedy barrios unidos", "caobos cedritos", 
                        "sabnta barbara central", "quiroga sur", "malibu niza", "granja norte", "bachue", 
                        "cedros santa cruz sierra", "santa brbara baja", "carval osorio", "claret", "delicias", 
                        "sierras moral", "lisboa usado", "parkway", "villemar", "portus alejandria", 
                        "colina bosque verde balcones", "ciudad salitre occidental", "ferias", "galeras", "lagos crdoba", 
                        "patio bonito", "recuerdo", "alameda country", "calatrava", "cedro salazar", 
                        "pepe sierra norte", "bellisimo santa barbara", "parques san martin", "townhouse carolina", "bacata", 
                        "colegio jazmin pte aranda", "teusequillo", "salitre oriental", "alicante mosquera", "pinos florencia", 
                        "serrana salitre oriental", "parque central", "malibu alhambra", "mirandela", "villa alsacia kennedy", 
                        "santa coloma", "redil", "cedritos cedritos", "parque club", "centro internacional", 
                        "sierra", "cedros cedros tramite", "santa teresita teusaquillo", "versalles", "prado veraniego", 
                        "bulevar niza", "belen malibu", "san carlos kennedy", "carvajal kennedy", "bella timiza", 
                        "park way", "granada club", "calleja alta country", "chico navarra colombia", "san antonio noroccidental mirandor alameda", 
                        "sector cortijo arces rojos", "victoria norte", "campo alegre santa barbara", "san cipriano", "altos lagartos", 
                        "aloha bavaria", "cedritos aranjuez", "santa barbara pepe sierra", "quesada", "morato", 
                        "fuentes dorado", "batan ii sector", "alejandria mazuren", "roma", "cervantes kennedy", 
                        "lucerna", "villa nelly", "almenar", "alsacia bavaria", "titan plaza", 
                        "recreo", "ginebra", "san martn", "vargas", "alcal", 
                        "acapulco", "lagos cordoba niza", "sobriedad tranquilidad san patricio", "macarena san diego", "bonito puente", 
                        "soho", "buganvilla unicentro", "palatino cedritos", "chico navarra balcones", "cedro madeira cedro golf", 
                        "boyac real", "cabana ferias", "urbanizacion coruna", "espaola", "niza cordoba", 
                        "cerros country", "delmonte", "libertador rafael uribe uribe", "san cristobal alto", "macarena", 
                        "alquera", "libertad norte barrios unidos", "modelo norte barrios unidos", "modelia balmoral ii", "salitre noroccidental", 
                        "pio banderas", "palenque kennedy", "verona", "san martin norte", "santa ana occ", 
                        "bosque lagartos", "santa brbara central", "esperanza", "andes cuadrados", "malib alhambra", 
                        "sector santa barbara", "patria", "unicentro santa barbara", "arrendar", "carolina country club", 
                        "santa barbara ocidental", "torres parque macarena", "barrrio santa maria lago", "sector alameda norte", "belalcazar palermo", 
                        "jota vargas", "san jose bavaria", "ciudad cali", "cercano hacienda santa barbara", "sector corferias", 
                        "chapinero san luis", "madelena", "laguneta venecia", "tejar", "ponderosa", 
                        "olivo kennedy", "altos santa ana", "milla oro", "carlos lleras", "carmen", 
                        "penon girardot", "ferro caja", "villa delia britalia norte", "samper mendoza", "chucua", 
                        "rincon venecia venecia", "ciudad jardn sur", "administracion", "villas mediterraneo", "molinos norte santa barbara", 
                        "balcones santa barbara", "nilo", "san luis teusaquillo", "monjes santa cecilia", "batn ii sector", 
                        "amricas", "niza atabanza", "santa catalina castilla kennedy", "marsella kennedy", "ciudad alsacia", 
                        "estrella norte", "florida blanca alamos", "san martin quinta centro", "horizonte santa barbara", "sta barbara occ", 
                        "serramonte", "fatima venecia", "floresta rio negro", "colina mazuren", "tibabita", 
                        "ciudad sector cedros", "felicidad cumbre", "felicidad riviera", "tintala kennedy", "carvajal osorio", 
                        "kennedy dindalito", "batan colombia", "santa barbara central colombia", "faro alejandria", "hacienda cordoba niza ix", 
                        "lindaraja", "colina norte", "roma kennedy", "villa rio", "igualdad kennedy", 
                        "floralia kennedy", "estancia macrosur", "universidad agustiniana", "kennedy villavicencio mayo", "carvajal", 
                        "cabana boyaca", "santa rosita", "santa rosa", "bosque popular", "cabaa", 
                        "villas dorado", "tierra grata", "santa maria lago", "faena", "zarzamora salina", 
                        "clarita", "villa claver ii", "florida blanca", "primavera norte", "centro nario", 
                        "ciudad jardn", "alfonso lpez", "patio lisboa", "campina", "penhouse santa barbara occidental", 
                        "sant barbara", "balcones oriente", "santa barbabara", "mallorca", "venecia occidental tunjuelito", 
                        "salvador", "loma escobero", "aguacatala", "san jose mosquera", "bacata cacique funza", 
                        "calasanz medellin", "vereda piedra", "olarte", "torremolinos", "prados kennedy timiza", 
                        "francisco miranda", "bonanza ferias", "alhambra monaco", "corinto alejandria", "julio florez", 
                        "americas", "marsella iii sector", "occidente", "puerto libertador cruces", "scala", 
                        "sector salitre", "nicolas federman barrios unidos", "chico nvarra", "puente aranda torre molinos", "colina norte ii etapa colina campe", 
                        "florencia", "santa marta pastrana kennedy", "villas granada mortino", "campina palo alto", "san nicols", 
                        "santa barbara centro", "vina mar", "san patricio parque francia", "alejandria azimut", "cedritos manzana verde", 
                        "torre hayuelos", "iberia colina campestre", "villa rosas cedros", "mazuren gimnasio", "spring", 
                        "campin", "modelo", "cedro verde cedritos", "cipres arboleda salitre", "sta barbara oriental", 
                        "calleja penthousse", "contador contador", "moraika alameda", "santa barbara balcones", "cantalejo sector alejandria", 
                        "macahuba country", "esquilero bella suiza", "chico navarra norte", "cedritos cedro golf", "bosque", 
                        "espectaular santa barbara oc", "porto americas", "mazuren alejandria", "centenario", "carolina prado alto", 
                        "liberia", "rios andes", "ferrocajas", "bosques modelia", "dorado", 
                        "quiantas santa barbara", "atenas prado", "argenta colina campestre", "bosques ferrol", "cedro", 
                        "bella suiza alta balcones", "santa barba oriental", "tierra", "cedritos uaquen", "magdalena teusaquillo", 
                        "sangta barbara oriental", "piemonte provenza", "multicentro santa barbara", "lisboa alameda", "cedros cedritos", 
                        "capri cedritos", "cedro narvaez cedros", "muequeta alcazares", "palermo manizales", "quinta mutis", 
                        "pablo vi", "ciudad jardin norte", "club lagartos", "kenendy boyaca", "selva dorada san pablo", 
                        "ciudad jardin ciudad jardin", "san patricio santa barbara", "lisboa bogotaa", "san martin sagrado corazon", "salitre nor occidental ciudad salitre occidente", 
                        "carvajal ii sector americas", "altos chozica", "sn jose obrero", "vereda chuntame cajica", "sabana centro chia", 
                        "portoalegre", "sector modelia", "san diego", "santa bibiana balcones", "buganvilla santa barbara", 
                        "palenque timiza kennedy", "margaritas cedritos", "rincon puente", "simon bolivar barrios unidos", "sol gratamira", 
                        "prado", "bario colina campestre", "colina campestre picasso", "sorrento", "iraka bella suiza", 
                        "rincon margaritas", "rincon alameda", "santa lucia norte", "cofradia", "plaza americas", 
                        "cedro golf cedros", "gloria lara", "barrios unidos", "jose joaquin vargas", "santa barbara vii cortijo", 
                        "interesante modelia", "toscana hayuelos", "condado iberia", "colina occidental", "kennedy kennedy central", 
                        "ciudad kennedy sur kennedy central", "sta isabel occidental", "antigua", "acevedotejada", "alaska", 
                        "niza viii", "alta blanca", "capellania", "cedritos sur", "altos sotileza", 
                        "trinidad galan", "muzu muzu", "cofradia modelia", "santa barbara occidental santa barbara", "mota", 
                        "capri cedros", "esperanza sur", "monaco", "margaritas sect ii", "villa alsacia bavaria", 
                        "montemadero", "kanna iv", "caney sta barbara", "carolina unicentro", "colina campestre cbota", 
                        "sotileza cerros provenza", "villa elisa", "colinas casablanca", "marsella ii iii", "mandalay sector", 
                        "aloha", "lisboa norte", "sta paula", "sofia quinta paredes", "sanpatricio", 
                        "americas etapa", "florida", "ciudad kennedy occidental kennedy central", "arboleda felicidad", "laureles sauzalito", 
                        "rincon iberia", "villa claudia", "sta barbara central", "unicentro hacienda santa barbara", "embajada eeuu", 
                        "madrigal", "bosa", "atalanta villa alsacia", "hacienda", "serena minuto dios", 
                        "monticello", "valbella", "belmira sector alameda", "buganvilla", "marsella ii iii sector", 
                        "olaya quiroga", "guali", "gaco granada", "alameda san antonio", "hayuelos sabana", 
                        "gaco", "entrerios", "riviera", "ibague", "santa barbara patio", 
                        "parque calleja", "santa helena prado", "floralia ii sector", "tequedama kennedy", "patio bonito kennedy", 
                        "maria paz kennedy corabastos", "pablo vi teusaquillo", "metrpolis", "torcoroma", "tibana", 
                        "san eusebio", "lotes san gil", "bellavista occidental", "asturias", "acapulco ferias", 
                        "villa claudia kennedy", "batan alhambra", "pinar", "villa rio kennedy", "ciudad sector cedritos", 
                        "granada villas granada", "olarte bosa", "icata club", "parques tibana puente aranda", "normandia cantabria", 
                        "paraiso castilla valladolid kennedy", "bosques ferrol marsella", "rioja", "colseguros", "toscana moderna remodel", 
                        "santa barbara central norte", "sector castilla", "recody country", "san patricio parque", "santa barbara vii" 
)


neigborhood_list_3 <- c("alqueria fragua bgta", "eduardo santos", "san fernando barrios unidos", "timiza", "salamanca", 
                        "villanova", "rosario", "bosa santa fe", "argelia", "kennedy roma", 
                        "castilla kennedy", "bosa tropezon", "semi bosa centr", "bosa centro", "septor mandalay patos", 
                        "catalina kennedy", "kenedy", "bosa paraiso", "bosa brasil", "san francisco", 
                        "ibague tolima", "cedritos capri", "colon", "minuto dios minuto dios", "san jose spring", 
                        "catalina sector kennedy", "salitre nor occidental", "jos joaqun vargas", "carlos lleras restrepo", "salitre sauzalito", 
                        "sector quinta paredes", "tamesis portal norte", "apolo iii", "nicolas federmann", "belmira par", 
                        "cerrad mojana", "bosq canada", "ceja", "bravo paez", "calido santa barbara", 
                        "cercania fundacion santa fe", "calleja unicentro", "buganvilla sector", "retiro santa monica", "santa barbara molinos norte", 
                        "cerros orientales", "cedritos altos moral", "crecer", "retiro santa monica unicentro", "macarena bosque izquierdo", 
                        "centro sector", "sector galan", "centro comercialcarrera", "campin sector galerias", "labrador", 
                        "rionegro", "ferrocaja", "zarzamora boyaca real", "viva modelia", "san marcos villa", 
                        "terreno", "provenza cerros", "atabanza", "comoda colina campestre", "marsella ii americas", 
                        "palermo teusaquillo", "pance scala", "cima alcala", "santa barbara unicentro", "villa aranjuez", 
                        "uribe", "centro macarena torres parque", "esperanza modelia", "batam", "antigua helvetia", 
                        "pio xii", "proviendo oriental kennedy", "modelia bohota", "pilarica medellin", "altos moral", 
                        "madalay", "galerias colombia", "sector barrancas", "club contry contador", "aguas", 
                        "torremolinos puente aranda", "fontino", "blanca", "santa maria calatrava", "provenza", 
                        "alamos angeles ii", "jazmin", "pontevedra sector", "granada norte", "contador rahx", 
                        "cedritos belmira", "caobos", "liberia parque", "felicidad multiplaza", "modelia santa cecilia", 
                        "parque bavaria", "torres molinos", "contador norte", "cuidad salitre", "poblado medellin", 
                        "parkway soledad", "san cayetano", "sector americas", "centro narino", "ciudad kennedy central", 
                        "samper centro internacional", "palermo teusaquillo catolica", "bellisima sector san cipriano", "monterrey", "santacoloma calleja baja", 
                        "chico navarra parque", "carolina norte", "primavera ii", "capilla antigua", "merced", 
                        "concepcion norte", "marsella alhoa kennedy", "pino", "san martin quinta", "timiza kennedy", 
                        "cedritos alcala", "ensanta barbara occidental", "sta matilde", "sana tranquila", "laureles acacias medellin", 
                        "villa rio bosa", "kennedy cental", "icata norte", "santa brbara ii", "santa brbara unicentro", 
                        "calleja santa coloma", "santa clara", "alcazar san luis", "puerto", "kaquelin socorro kennedy", 
                        "tunjuelito", "kennedy blanca", "centro int parque central bavaria", "barrios unidos simon bolivar", "polo clud", 
                        "santa bardara", "muz", "venecia tunjuelito", "rincon andes", "norte colombia", 
                        "club icata", "villa arajuez", "marques ii cedritos", "chia chilacos", "barranquilla andes", 
                        "progreso santa isabel", "parques normandia normandia", "quita paredes", "mochuelo", "doral", 
                        "tobern", "cerros niza", "ciudad berna", "pensilvania", "juan xxiii", 
                        "venevia", "terraz", "chico navaraa", "balcones", "salitre alto ciudad salitre", 
                        "prado felicidad", "sector mazuren alejandria", "llanura", "villa leyva", "valladolid", 
                        "palmas", "atenas blanca", "puente aranda ciudad montes", "country cedros", "sotavento", 
                        "ciudad kennedy oriental", "san jorge marco fidel suarez", "andes andes", "sorrento cedro narvaez", "flora alsacia", 
                        "concordia", "santa paula parque", "urbanizacion castilla", "santa catalina kennedy", "modelo sur", 
                        "sta barbara alta", "alcazares norte", "salitre luis maria fernandez", "caobos narvaez sorrento", "bravo paez marco fidel suarez", 
                        "cedritos cedros", "bosque pino", "salitre alta", "prado veraniego sur", "miguelines", 
                        "amrica teusaquillo", "san esteban castilla", "alkala", "prados sabana", "continental", 
                        "cervantes", "primavera", "terrazas ciudad salitre", "senderos carmel", "andalucia", 
                        "morisco minuto dios", "marandu", "ciudad jardin sur", "bellisimo calleja", "quesada teusaquillo", 
                        "noviembre", "luis carlos carlos", "accanto club colina campestre", "claret ibague", "colonia oriental", 
                        "agosto barrios unidos", "sta isabel", "caobo salazar", "belmira lisboa", "grados", 
                        "penthose hayuelos", "contry club", "salitre plaza", "teusaquillo park way", "golf recodo country", 
                        "igualdad", "teusaquillo santa teresita", "carval", "rincon venecia", "occidente san jose bavaria", 
                        "tintal castilla", "cedro norte", "multicentro hall", "san antonio sur", "azimut alejandria", 
                        "high park", "picabia mazuren", "castilla rincon angeles", "poblado", "santa barbara cortijo", 
                        "bella suiza iraka", "marcofidel suarez", "bosque colina", "colina san rafael", "bosque caada", 
                        "sabanilla", "santa barbara patio interno", "torres majui cedros", "ciudad kennedy sur", "nicolas federman esmeranda", 
                        "potosi suan", "ibague sexta", "torrecolina mazuren", "torres majui", "arboleda salitre", 
                        "san joaquin norte", "blanca sector", "san cristobal", "salitre rioja", "polo cluub", 
                        "felicidad sabana", "sector colinas", "villas aranjuez galileo", "cedritos balcones", "altos rincon alameda", 
                        "cedros parque", "puente aranda verona", "camelia sur san rafael", "benjamin herrera alcazares", "parques san jeronimo gaco", 
                        "parque central ciudad salitre", "santa cecilia", "spazio", "santa barbara pino", "torre bosque izquierdo alto", 
                        "contry", "esperanza norte", "carlos restrepo", "parque cipreces", "liberia toberin", 
                        "kennedy hipotecho sur", "vinta villa alsacia", "mazuren balcones", "pio xii castilla", "eduardo frei rafael uribe", 
                        "sector margaritas", "buganvilia cedritos", "refugio ciudad bosque", "lagos cacique bucaramanga", "muequeta", 
                        "salitre maloka", "villa nova", "encantadora", "serramonte cerros orientales", "palestina", 
                        "san diego santa fe", "santa isabel sur santa isabel", "cordoba niza", "veraguas santa isabel", "quintaparedes", 
                        "central park", "calima", "pablo sexto", "cedritos liberia", "conservacion chapinero", 
                        "salvador galerias", "norte santa barbara", "quintaparedes embajada americana", "kennedy norte", "carimagua", 
                        "bosque medina bonito", "acacia", "pasadena parque", "salitre fuentes salitre", "coruna sur", 
                        "palmar rio", "bonito cedritos", "aguas claras san blas", "norte medellin", "campin galerias", 
                        "chucua kennedy", "alqueria", "versalles mazuren", "villa adriana", "santa helenita boyaca real", 
                        "villa gladys", "alpes barranquilla", "andes norte control domotico", "penhouse mazuren", "lagos", 
                        "quiroga central", "belmira country", "parque santa barbara occidental", "pradera norte san roque", "santa cruz sierra cedros", 
                        "caminos san roque pradera norte", "torres modelia", "torres obelisco", "sauzalito", "alto riomar", 
                        "jj vargas", "constructivo", "perdomo", "sector normandia", "palermo galerias", 
                        "villa magdala toberin", "mayo", "modelia esperanza", "parque santa ana", "bosques alameda ii", 
                        "versalles colina campestre", "amoblar san patricio", "remanso", "provivienda", "villa quiroga", 
                        "catalina", "villa ines", "cabana", "alquerias fragua", "san jose sur", 
                        "nieves tadeo", "ayacucho kennedy", "cota cundinamarca", "calamari", "kennedy carvajal plaza americas", 
                        "llanurita kennedy", "santa monica medellin", "villa azafranes", "panorama", "san miguel barrios unidos", 
                        "alcaparros", "bavaria", "santa catalina sector ii", "patricio", "toscana", 
                        "sant barbara central", "estacion", "sector ciudad jardin", "santa cruz salitre", "alqueria fragua", 
                        "carimagua sector", "prado veraniego norte", "antigua lisboa", "cedritos norte", "kennedy palenque", 
                        "tintal", "cambulos", "santafe pijao zelandia", "bavaria kennedy", "bella suiza terrazas", 
                        "nicolas federman teusaquillo", "santa maria", "colina campestre terraquinta", "cedrito", "colina guayacanes", 
                        "santa brbara occidental", "san jorge central", "parques colina", "san patricio alto", "amrica", 
                        "country club calleja", "miraflores parque", "santa occ", "fusagasuga cundinamarca", "cristales carvajal", 
                        "catalina ii timiza", "techo kennedy central", "corferias quintaparedes", "san patricio terrazas amplias", "danubio", 
                        "aguas candelaria", "medellin sector poblado", "belmira cojunto", "pepita", "britalita bosa", 
                        "arabia", "recodo", "campn", "villa calasanz andes", "boita kennedy", 
                        "marsella iii", "veracruz", "niza viii niza", "sector calleja", "capellania esperanza boyaca", 
                        "parques modelia", "batan norte", "frontier", "salitre oriental ciudad", "torres capellania", 
                        "santa sofia alcazares", "entrerrios andes", "martirez eduardo santos", "bosa villa rio", "santa helena baviera", 
                        "alhambra malibu", "santa teresa norte", "paz centro", "navetas", "colombia nieves", 
                        "gallery lagartos", "campo patio bonito", "orquideas toberin", "lisboa country", "mojana cedritos", 
                        "san vicente", "arrayanes normandia torre campo", "pasadena gimnasio", "bella", "altos colina", 
                        "camilo torres", "tequendama", "dragma iv carolina", "mirador alameda", "paris", 
                        "san roque", "bosques granada", "mortino", "oasis", "aures ii", 
                        "tabora", "granada club residen dorado engat", "centro internacional torres paque", "cedral", "torre", 
                        "bosque country", "carlos llerras", "villa prado cali valle cauca", "alambra", "rincon cedro", 
                        "cedritos sector norte", "ciudad salitre sur oriental ciudad salitre oriental", "felicidad pinos", "puerto vallarta", "pomerol", 
                        "ciudad salitre san sebastian andes", "plaza real ii", "san gabriel", "castilla mirador san esteban", "recodo country parque", 
                        "villa claver", "cuidad", "alameda bosque", "pinos marsella", "corferias", 
                        "modelia cipreses", "santa rita puente aranda", "santa barbara central unicentro", "acevedo tejada teusaquillo", "kennedy olivo", 
                        "villa nelly kennedy", "mendoza", "sector norte cedrito", "parque alcala", "funza trojes", 
                        "bosque modelia modelia", "calleja country", "sagrado corazon", "jorge eliecer gaitan sector", "urbanizacion san martin", 
                        "salitre puerto vallarta", "entrecedros", "centro tadeo", "andes barrios unidos", "taberin", 
                        "san martin porres", "sector bosque medina cerros", "lucerna kennedy", "centenario quiroga", "quinta ramos san cristobal sur", 
                        "cedro golf alta blanca", "reliquia ferias", "veraguas mrtires", "campin occidental esmeralda", "molinos norte bonito", 
                        "plaza bosque", "portoamericas", "panorama cedritos", "puente aranda terreno", "castellana norte", 
                        "monjes", "villa maria", "niza norte sector", "santa catalina", "tejar angeles", 
                        "isla sol", "bosa clarelandia ciudad", "roma iv ciudad", "villa flor yopal", "san diego centro", 
                        "hacienda blanca yopal casanare", "sector bochica central", "berlin kennedy", "parque salitre modelo norte", "salitre torres alba", 
                        "europa normandia", "normandia boyaca", "santa cecilia ciudad", "floraria ciudad", "pastranita kennedy", 
                        "marsella boyaca americas", "carvajal llanura mayo", "catalina ii ciudad", "catalina kennedy ciudad", "boita", 
                        "villa emilia", "villa nelly villavicencio abastos", "sector igualdad", "camilo torres kennedy", "carvajal ciudad", 
                        "campina sur", "sector kennedy", "cedritos palatino", "cedritos akaroa", "santa barabara occidental", 
                        "bella suiza alto", "calleja balcones", "favorita", "altos belmira", "torresol santa barbara", 
                        "unicentro occidente", "santa barbara baja", "cucuta", "contador cedros", "sector contador", 
                        "niza villas", "colombia barrios unidos", "mirador santa helena", "san luis chapinero", "lujan", 
                        "alsacia kennedy", "bellisimo cedritos", "slcobas buya cerros", "batan kra", "boyaca paseo", 
                        "ingles", "madelena fusagasuga", "santa bibiana chico", "norte bucaramanga cali", "country club chia sabana", 
                        "cedritos modelia", "unicentro sabana", "villas prado", "soledad park way", "jj vargas finca sabana cundinamarca", 
                        "quirinal privados", "colsubsidio", "demoler", "alamos torrecampo", "apulo anapoima mesa tocaima", 
                        "fusagasuga vega girardot medellin", "san bernardo fusagasuga", "malaga castilla", "kennedy pastranita", "marco fidel suarez" 
)


neigborhood_list_4 <- c("luna park", "narino sur", "cruces", "veraguas central", "villamaria", 
                        "parque periodistas", "carolina parque country", "kennedy carimagua", "kennedy almenar", "kennedy mandalay", 
                        "centro parque central bavaria", "almera", "alameda usquen", "jiralda", "villemar fotibon", 
                        "parques cortijo", "urbanizacion san cayetano", "potosi ii sector", "valle refous", "colina campestre alameda santa clara", 
                        "paris gaitan", "torre campo", "bosque cali", "terrazas belmira cedritos", "morada", 
                        "bolivia real", "castilla calatrava", "sector polo club", "alborada", "ciudad bachue minuto dios", 
                        "camino san roque pradera norte", "cedros oriental", "vereda calahorra cajica", "alquerias fragua sector", "merced sagrado corazon", 
                        "norte villapinzon", "monte pinos", "san patricio norte", "ruby", "colores medellin", 
                        "verde zotileza", "siberia", "santa librada", "equilibrium centro san martin", "aranjuez cedritos", 
                        "contador iii", "campin oc", "vereda rincon", "espectalular altos sotileza", "boston", 
                        "sp santa barbara", "vereda cerros", "monte", "pilarica medellin antioquia", "castellon conde tintala calandaima", 
                        "cedros oriental cedros", "recreo frailes alhambra", "hayuelos modelia", "margaritas cedros", "concordia candelaria", 
                        "patria andes", "jorge eliecer gaitan octubre", "tejar muzu", "villa sonia ii bosa occidental", "dorado san joaquin ferias", 
                        "quirigua minuto dios", "ciudad kennedy central kennedy central", "villa restrepo", "san eusebio ciudad montes", "san marcos santa cecilia", 
                        "juan xxiii norte alcazares", "colina campestre oc", "cedro bolvar", "campanario batan", "coutry", 
                        "quirigua san jorge norte", "santa barbara sorrento", "ciudad salitre teusaquillo", "modelia imperial", "santafe", 
                        "cedritos cedro", "claret rafael uribe uribe", "palmar", "clinica nogales", "sector hayuelos", 
                        "clinca vascular navarra", "san jorge central ii sector", "mayorca hayuelos", "terrazas bella suiza", "felicidad modelia", 
                        "belalcazar universidad nacional", "salitre carlos lleras", "cedritos lisboa", "santa barbara norte", "normandia ii sector", 
                        "santa helena mazuren", "recreo frailes batn", "barranquilla", "poblar colina campestre", "parques san jose prado", 
                        "torres granada iberia", "maria paz", "concordia corabastos", "norte sector bosque medina", "san gabriel norte", 
                        "country plaza", "cedros primavera", "sata barara", "sol", "frontier centro", 
                        "bellaire acacias", "contador ms", "castilla san esteban", "normandia ii", "demoler galerias", 
                        "sur", "nvo country", "bosques country", "santa barbara oc", "salina", 
                        "tejar puente aranda", "niza sur ii etapa", "torino cedro", "tejares norte", "lausiana", 
                        "prado camelias santa teresa", "colina campestre iii iv", "villa kennedy", "ayacucho", "gallery lagartos niza", 
                        "contador jardin", "parque sta barbara", "santa barbara buganvilla", "mirador alameda san antonio noroccidental", "cedritos golf", 
                        "rincon", "galan americas", "centro recoleta san diego", "san gabriel iii", "bella suiza balcones", 
                        "palermo manizales caldas", "sector patio bonito", "vision colombia kennedy", "rosales cedro golf", "poblado bquilla", 
                        "castilla concado", "canodromo", "lombardia", "soledad teusquillo", "sector hayuelos mayorca", 
                        "galerias teusaquillo patio", "colinas provenza", "cipres", "marsella portoamericas", "bella suiza occidente", 
                        "palmanova", "centro commercial plaza central", "villa teresita", "tuna alta", "salitre parque", 
                        "ciudad salitre riveras parana", "florencia boyaca real", "contador cedritos", "sector unicentro", "alamos angeles", 
                        "paseo", "fusagasuga plaza mercado", "kennedy marsella", "tintala castilla kennedy", "castilla alsacia", 
                        "carimagua kennedy", "lagos cordoba parques provenza", "rios barrios unidos", "tintala calandaima", "bosque castilla", 
                        "portal patio bonito", "quinta ramos", "campina restrepo", "ciudad jardin", "policarpa", 
                        "eduardo frey", "ospina perez", "pradera puente aranda", "muzu ospina perez", "villa gladis", 
                        "campestre carmen apicala", "santa bibiaba", "senderos salitre", "kennedy palenque timiza", "campestre girardot ricaurte cundinamarca", 
                        "espectatular niza", "parque portoamericas kennedy", "cedros villa rosas", "cedros deco", "modelia occidental modelia", 
                        "metropolis ferias", "glorieta", "sector santa paula", "chico santa bibiana", "sector lisboa", 
                        "sector bosque medina", "bosques medina", "excluviso cedritos", "ricaurte", "pinos", 
                        "sector esperanza", "sector niza norte", "cajica", "sector iberia", "sector colina", 
                        "sector caobos salazar", "camino arrayanes", "altos provenza niza", "corinto", "refugio alto", 
                        "niza altos provenza", "torreladera", " niza", "recreo frailes sector batan", "miraflores", 
                        "verde cedritos", "anuncio prueba", "prueba destaque", "ciudad salitre santa maria", "pradera norte san cristobal norte", 
                        "britalia sur", "colina campestre iberia", "country norte", "modelia salitre", "sta barbara central abaraki", 
                        "carvajal provivienda oriental", "historica", "quinta paredes inmobiliario", "bolivia oriental", "villa castilla", 
                        "cafam floresta", "torres valencia santa rosa", "santa ana pepe sierra", "santa barbara occ terrazas", "multicentro buganvilla", 
                        "parque empresarial occidente", "nogales rincon", "macahuba country calleja", "ponderosa puente aranda", "cerros oriental", 
                        "floresta morato", "sector restrepo", "portico", "manzana bolivia", "acantto colina", 
                        "bosa clarelandia", "restrepo restrepo", "santa viviana", "villas rosas", "museo parque central torre alta", 
                        "ciudad montes patio", "palestina minuto dios", "santa lucia quiroga", "partamento chico navarra", "baleares modelia", 
                        "normandia santa cecilia", "morada jamundi", "toberin toberin", "carolina iii tibabuyes", "santander sur", 
                        "alfonso lopez galerias", "villa amalia", "valle", "capellania central", "belalcazar teusaquillo", 
                        "lago timiza ii etapa", "samper", "condado castilla", "trinidad puente aranda", "olaya", 
                        "botanica", "caobos salazar cedro narvaez", "rios tulua", "modelia imperial iii", "andes norte sector", 
                        "lago club lagartos", "clarita ciudad cali cita", "estacion venecia", "calleja zebra norte", "albatroz carolina", 
                        "parque salitre", "santa barbara saturno", "teusaquillo triveca", "colina campestre casigua", "tiban", 
                        "puerta teja", "esmeralda teusaquillo", "amricas occidental", "cedritos icata", "boit", 
                        "maratu", "castilla castelo", "prados castilla", "castilla imperial", "bonito villa alsacia", 
                        "barichara centro", "villa teresa", "torres aranjuez", "santra barbara", "colina campestre lr", 
                        "urbanizacion cordoba niza", "palenque timiza", "jordan", "acacias cedros", "think bosque izquierdo", 
                        "santa barbara central ii", "cedritos caobos", "fontana plenitud", "carolina plenitud", "plenitud carolina", 
                        "tejares santa fe", "moderna niza cordoba", "restrepo centenario", "santa barbara kr", "estadio atahualpa", 
                        "villa alsacia eden multiplaza boyaca", "villa alsacia eden multiplaza", "cedro golf homecenter", "villa ro bosa", "amparo", 
                        "kennedy amparo", "nqs rio negro", "cedritos villa magdala patio", "diver plaza", "ferias colegio magdalena ortega narino juan", 
                        "felicidad centro multiplaza", "potosi titan plaza", "colina campestre poblar", "helios", "babilonia", 
                        "ingles quiroga", "granada ii", "pinares alsacia", "lisboa cedritos bosque", "santa barbara unicentro multicentro buganvilla", 
                        "unicentro calleja baja", "tequendama centro internacional", "cipres modelia", "batan jardin", "cerros lagartos", 
                        "floresta sur kennedy", "chico navarra oc", "alcazares barrios unidos", "villa rosario puente aranda", "murillo toro quiroga", 
                        "teatro teusaquillo", "hipotecho sur kennedy portoamericas", "sector marsella", "karim", "orquideas norte", 
                        "aitana salitre modelia", "aitana salitre esperanza", "santa barbara ii etapa", "tuna baja", "pasadena emely", 
                        "sector colina campestre", "pasadena oscar", "karim pasadena", "milza", "parques", 
                        "entreparques", "pereira", "san francisco sur", "parquedero plaza americas kennedy", "primavera cedros", 
                        "quinta mutiz barrios unidos", "san luis sur san jose", "calleja padua", "carolina country", "chico navarra patio interno", 
                        "refugio ciudad", "carolina jardin", "ciento nueve quesada", "ciudad salitre oriental ciudad salitre oriental", "carmelo", 
                        "alcazar castilla", "aurora barrios unidos", "babilonia toberin", "jorge gaitn cortes puente aranda", "cedritos aqua", 
                        "villa javier cundinamarca", "villanueva", "contador verde", "ch navarra", "sector castellana", 
                        "san basilio", "minuto dios tulipanes", "plano", "calera", "torres villa alsacia kennedy", 
                        "bosques pinos", "galerias empresas", "country lisboa", "lijaca", "michella sotomayor", 
                        "armenia teusaquillo", "carabelas puente aranda", "malcobas", "acacias belmira", "sociego sur", 
                        "cedritos sol", "mazuren cajica chia", "centralisima castilla", "delicia", "paratmento sierras moral", 
                        "cedro navarra musa", "esperanza cucuta", "ciudadela felicidad", "montecarlo iii mazuren", "bonito mazuren", 
                        "miramont club", "car lleras restrepo esperanza sur", "valladolid castilla kennedy", "san antonio norte verbenal", "calleja parque", 
                        "coln", "park hayuelos", "bella sauiza", "colseguros andes sur cali", "refugio norte florida", 
                        "entrerros", "bochica central ii", "doce octubre", "guaymaral", "noroccidente", 
                        "san jose obrero", "murillo toro", "felicidad boyaca", "alfonso lpez teusaquillo", "san remo sta barbara", 
                        "bosques caada", "ciudad salitre nor oriental teusaquillo", "sector batan", "marsella ferrol kennedy", "hipotecho sur parque recidencial kennedy", 
                        "santa ana sur", "calvo", "villa sonia", "cedros orientales", "santa isabel vergel", 
                        "sector envigado san lucas", "buganbilla", "internacional", "salitre noroccidente", "niza noroccidente", 
                        "parque central bavaria centro", "nieves centro", "villa alsacia castilla occidente", "salitre alto", "santa marta", 
                        "suenos bella suiza", "libertadores", "restrepo occidental", "castilla valladolid", "rosario barrios unidos", 
                        "centro periodistas", "cantagallo", "kennedy california", "floresta sur", "hayuelos viva", 
                        "nario sur", "nario sur san cristobal sur", "villas mediterrneo", "teusaquillo campin", "sabra barbara central", 
                        "metropolis simn bolivar", "iraka", "vereda fagua", "magdalena", "americas boyaca", 
                        "sausalito", "multicentro norte", "aguas centro", "quesada centro", "bonanza occidente", 
                        "campestre melgar cita", "ferias colegio magdalena ortega narino juan corral", "garces navas occidente", "milenta sur", "galerias centro", 
                        "cedro golf norte", "villa aranjuez nororiente", "ciudad kennedy norte", "san paula", "rincn venecia", 
                        "prado country", "colonial centro historico", "bodegas carvajal", "socorro", "san pablo", 
                        "santa barbara occi", "colombiano", "veraguas occidental", "calleja norte", "cedritos cedro bolivar", 
                        "santabarbara", "americas plaza americas", "moderna", "floresta sur igualdad", "santa barbarra", 
                        "urbanizacion santa coloma", "esperanza modelia occidente", "mazal unicentro", "san eusebio sur", "salitre centro", 
                        "colina campestre noroccidente", "villavicencio abastoss", "restrepo sur sector central", "bosa nova", "verbenal santa maria", 
                        "primavera puente aranda", "san jose granja", "pio mandalay", "montearroyo", "teusaquillo galeras alfonso lpez", 
                        "villas ii sector villas", "chapinero palermo", "laurel", "chapinero sur occidental", "tamesis", 
                        "bosque gratamira", "alameda antigua", "tarragona", "villa angeles castilla", "chia cundinamarca", 
                        "bravo paez rafael uribe", "miraflores kennedy", "metropolis metro", "alameda centro", "cedritos guadalmonte", 
                        "cerros norte", "narino", "parque alameda", "torres country", "rincon santo", 
                        "tunjuelito sur", "calleja cedro bolivar", "sector lombardia cedritos", "sector norte entrada", "martires", 
                        "ricaurte cundinamarca", "mallorca hayuelos", "modelia imperia", "ciudad salitre sur", "simon bolivar norte", 
                        "popular modelo norte", "piemonte", "pio xll", "cruces mrtires", "nororiente", 
                        "penon", "mallorca ii modelia", "cedro verde", "mrtires", "bosa olarta", 
                        "rafael uribe uribe murillo toro", "mrtires paloquemao", "barrios unidos campin", "remanso puente aranda", "centenario rafael uribe uribe", 
                        "cedro betira", "timiza occidente", "tundama", "semi kennedy central", "sector country", 
                        "belmira norte", "venecia muzu", "unicentro terrazas", "centrico", "kra", 
                        "chico infinity", "estancia", "pablo vi sector", "boit ii sector", "santacoloma", 
                        "san vicente ferrer sur", "corazon", "san patricio chico navarra", "sanpatricio santa bibiana", "santa paula patricio", 
                        "santa paula navarra", "santa barbara occiden", "sanfransisco sur", "eduardo sant", "sector multicentro santa barbara", 
                        "rincn angeles", "alta", "cerros alpes", "marat", "centro administrativo", 
                        "restrepo sur", "san jose sur sur", "libertador", "palo blanco", "cedro madeira"
)


neigborhood_list_5 <- c("cedritos santa teresa", "recreo fe frailes", "banderas", "villas rosario puente aranda", "tibana primavera", 
                        "barbara", "contador cedritos norte", "arrendar refugio", "centro colombia", "santa isabel occidental sur", 
                        "carvo sur", "ciudad berna sur", "antonio", "eduardo frei", "estanzuela", 
                        "san bernardo", "campestre nocaima cundinam", "villa nelly maria", "americas igualdad", "britalia noroccidente", 
                        "batan noroccidente", "refugio san antonio", "cedro norte norte", "universidad bosque bella suiza", "sensacional santa paula", 
                        "santa bibiana centro santa bibiana", "pontevedra titan plaza", "salitre modelia", "hayuelos capellania", "marsella antigua", 
                        "salitre alto cipres arboleda", "valle felicidad", "alcaparros sauzalito", "corazon trento", "norte colina camp", 
                        "niza calatrava", "americas occidental cervantes", "barrios unidos san fernando", "centroamricas", "centro internacional san martin", 
                        "encanto", "sector alameda", "parque cordoba", "bavaria techo ii sector", "portal amricas", 
                        "banderas pio xii", "lisboa norte cedritos", "castilla conjnto", "parques pontevedra", "palatino", 
                        "contador int", "pontevedra solarium", "centro aguas", "campia", "cedritos mary", 
                        "acasias", "campestre colinas", "belmiraa", "pablo sexto ii etapa", "cara", 
                        "santa helena", "kennedy carvajal", "kennedy boita", "villas granad", "batan parque nego", 
                        "marsella compuesta", "alcazar hayuelos", "abadia hayuelos sotano", "come", "remato molinos ruido", 
                        "alcala puente aranda", "kennedy lucerna", "laureles", "bellisimo rincon chico", "norte tamesis", 
                        "alameda palatino", "san victorino", "ciudad jardn antonio nario", "unal", "benjamn herrera", 
                        "parque central occidente", "quirigua rincon", "san jos sur", "lijac", "pontevedra lagartos", 
                        "pinos lombardia", "chica navarra", "san jos bavaria", "muzo", "sta paula mochuelo", 
                        "teusaquillo centro", "santa barbara bazaar", "modelia occidente", "gas cundinamarca santa barbara occidental norte", "bosques", 
                        "sociego", "cajica colombia", "sauces", "sector san jose bavaria", "san miguel norte", 
                        "santa catalina occidente", "campestre villa magdala", "colina camprestre", "alcal puente aranda", "bella suiza nororiente", 
                        "contador nororiente", "cedritos nororiente", "palenque", "sagrado corazn santa fe", "marcella", 
                        "san martin colombia", "vervenal", "niza sur", "marzo", "colina rincon granada", 
                        "isabela", "bellisimo sector felicidad", "dorado mosquera", "dorado funza", "villavicencio", 
                        "norte unicentro", "caobos salazar cedritos", "santa brbara centra", "lindaraja noroccidente distrito capital", "bosque medina terrazas", 
                        "torres parque", "kennedy occidental", "soacha", "villa rio sur", "santa barbara oriental norte", 
                        "niza real", "nicolas federman centro", "alamos norte occidente", "mandalay sector occidente", "salazar gomez sur", 
                        "vestier", "cedritos capri usaque", "chico norte chapinero", "quinto santa paula", "san carlos tunjuelito", 
                        "sana barbara central", "sector tequendama", "lagos cordoba noroccidente", "lagartos noroccidente", "villa mar", 
                        "parque central bavaria centro internacional", "bohios", "bravo pez", "santa sofia", "alsacia occidente", 
                        "cedritos caobos salazar", "chica norte ii chapinero", "torreladera blanca noroccidente", "villa claudia central", "santa coloma calleja", 
                        "country bella suiza", "centro internacional teleskop", "alamos sur", "ciudad jardin sur sur", "libertador quiroga", 
                        "villa javier sur", "cedritos mirador club", "soledad parkway", "cedro bolivar cedritos", "rafael ninez", 
                        "caobos salazar norte", "contador lisboa", "cedritos intimarka", "jazmin sur", "santa matilde sur", 
                        "granada sur", "ciudad kennedy central sur", "hipotecho occidente", "andalucia redil", "envigado", 
                        "america full", "colina norte iietapa colina", "carolina nororiente", "belmira nororiente", "cedritos margaritas", 
                        "santa barbara nororiente", "villa mediterraneo", "calleja alta nororiente", "caobos salazar nororiente", "santa barbara occidental nororiente", 
                        "barrancas nororiente", "calleja nororiente", "country nororiente", "santa barbara central nororiente", "norte cedritos", 
                        "parque cedritos", "orbba", "francia", "quirinal teusaquillo", "recuerdo teusaquillo", 
                        "modelo norte parque cipreses", "quinta paredes centro", "san miguel nororiente", "chapinero central chapinero", "hayuelos occidente", 
                        "hayuelos milano", "normandia occidente", "bella cortijo", "ciudad salitre nororiental centro", "san joaquin rojas", 
                        "capellania occidente", "carmen occidente", "kennedy britalia", "santa isabel martirs", "paris gaitan espanola", 
                        "floridablanca", "florencia paris", "milenio", "codito", "san martn santa fe", 
                        "torremolinos bella", "gaitana barrios unidos", "amparo kennedy", "roma rubi", "ciudad alsacia kennedy", 
                        "pueblo", "recuerdo centro", "rafael uribe uribe libertador", "san martin centro", "san patricio", "centro unicentro", 
                        "horizonte siento viento brilla sol", "loma parra sur oriental medellin", "santa barbara oriental nororiente", "salinas", "colina sanrafael", 
                        "retiro retiro retiro", "balsos sur oriental medellin", "seguro chico navarra", "icata nororiente", "santa barbara central buganvilla", 
                        "centro nariao centro", "alamos occidente", "soledad centro", "polo club nororiente", "villas madrigal occidente", 
                        "espera", "sector carabelas", "san luis centro", "bosque pinos norte", "imperial", 
                        "sn patricio", "sierras moral terrazas", "candromo", "san andres etapa", "costa azul", 
                        "andes floresta", "abadia hayuelos", "belalcazar chapinero", "norte davivienda", "altos salitre asturias", 
                        "lourdes", "conejera", "urbanizacin delicias", "urb mayo portal julio", "san jos", 
                        "germania", "castilla oro", "sta fe", "mochuelo norte", "dardanelos", 
                        "san patricio santa paula", "entrerrios barrios unidos", "castilla occidente", "villa alsacia bavaria occidente", "catalina occidente", 
                        "marsella occidente", "alquerias fragua occidente", "centro ciudad", "centro occidente", "mallorca occidente", 
                        "ciudad montes sur", "sta barabra occ", "santa bibiana chico navarra", "polo club norte", "primavera occidental", 
                        "flores", "mandalay etapa sector ii", "santaf", "villas noroccidente", "villa oriental sur", 
                        "claret quiroga sur", "aures noroccidente", "santa barbara occidental norte", "bosques canada norte", "santa ana occidental norte", 
                        "santa barbara alta norte", "rincon chico norte", "alameda noroccidente", "unicentro norte", "niza norte noroccidente", 
                        "pradera norte norte", "alameda reservada", "bosque medina norte", "torre alameda country", "santa barbara alta monteblanco", 
                        "cedritos contador", "country club norte", "chico navarra chapinero", "galan sur", "bosque izquierdo centro", 
                        "macarena santa", "campin centro", "santa rita sur", "remanso sur", "villa rosario sur", 
                        "candelaria centro", "carabelas sur", "quiroga central sur", "san jorge central ii sector sur", "sauces sur", 
                        "villa magdala norte", "fragua sur", "bochica iii occidente", "veraguas centro", "santa isabel sur", 
                        "santa isabel centro", "apulo", "egipto centro", "centro historico centro", "centro centro", 
                        "sector rionegro", "agosto norte", "cedro bolivar norte", "quinta camacho chapinero", "porciuncula chapinero", 
                        "patria norte", "granja occidente", "gaitan centro", "concepcion norte norte", "san martin noroccidente", 
                        "america centro", "benjamin herrera norte", "modelo norte occidente", "san felipe norte", "virrey norte", 
                        "macarena centro", "santa sofia noroccidente", "castellana sector", "belalcazar centro", "pinos marsella occidente", 
                        "lourdes centro", "centro internacional centro", "ciudad salitre occidente", "normandia occidental occidente", "estrada occidente", 
                        "bolivia occidente", "villa amalia occidente", "jose joaquin vargas norte", "ferias occidente", "cortijo occidente", 
                        "tibana sur", "bosque modelia occidente", "portales norte noroccidente", "salitre noroccidental occidente", "san jose bavaria noroccidente", 
                        "modelia occidental occidente", "vereda hato noroccidente calera", "igualdad ii sector occidente", "san joaquin occidente", "suesca suesca suesca", 
                        "barrios unidos noroccidente", "calera noroccidente calera", "santa maria lago noroccidente", "colinas noroccidente", "santa cecilia modelia occidente", 
                        "ciudad salite", "felicidad occidente", "nornandia", "san fernando norte", "sotileza noroccidente", 
                        "malibu alhambra noroccidente", "prado veraniego noroccidente", "alhambra noroccidente", "batan ii sector noroccidente", "kennedy ayacucho", 
                        "americas occidental ii iii occidente", "gratamira noroccidente", "altos sotileza noroccidente", "plaza americas sur", "alquerias fragua sector occidente", 
                        "etapa occidente", "rincon angeles occidente", "kennedy domo corredizo", "marsella ii iii sector occidente", "abraham lincon sur", 
                        "pio xii occidente", "ciudad kennedy sur sur", "castilla suroccidente", "americas occidente", "greco occidente", 
                        "galerias sector", "villa ines sur", "santa barbara portugal", "cajica cajica cajica", "margaritas nororiente", 
                        "san gabriel nororiente", "pozos colorados comuna santa marta", "igualdad occidente", "armenia centro", "cedro narvaez nororiente", 
                        "popular modelo nororiente", "villas mediterraneo nororiente", "guaymaral noroccidente", "san patricio nororiente", "portico noroccidente", 
                        "altos madelena", "miramont", "chico santa barbara", "cantalejo alejandria", "tamesis nororiente", 
                        "aguas sector", "santa fe centro", "vereda fagua chia chia", "villa magdala nororiente", "patria nororiente", 
                        "gloria lara echeverri noroccidente", "uribe nororiente", "alcala noroccidente", "andes noroccidente", "cedro bolivar nororiente", 
                        "bosque medina nororiente", "santa ana nororiente", "santa bibiana nororiente", "quirigua semicomercial", "magdalena centro", 
                        "bosque popular occidente", "sopo sopo sopo", "rio negro noroccidente", "chia chia chia", "villas dorado occidente", 
                        "palermo centro", "bosque pinos nororiente", "ginebra nororiente", "unicentro nororiente", "lisboa nororiente", 
                        "oocidente mercedces", "americas centro", "vereda chuntame cajica cajica", "esperanza nororiental chapinero", "molinos norte nororiente", 
                        "guaca sur", "valladolid castilla", "barranquilla barranquilla barranquilla", "santa maria lago occidente", "villa alpes sur", 
                        "samper mendoza centro", "plaza americas pago contado", "capri norte", "villas andalucia norte", "kennedy ayacucho sector", 
                        "ciudad salitre parque lineal sector", "floralia ii sector occidente", "santa ana niza noroccidente", "americas central occidente", "malibu niza noroccidente", 
                        "ciudad techo kennedy", "nocolas federman", "chia valle luna", "rincon angeles castilla", "castilla banderas", 
                        "rafael nunez iii", "macarena santa fe", "catalina ii kennedy", "recreo frayles", "arrayanes moraverde ii", 
                        "san andres venecia", "batavia", "kennedy patio bonito", "ayacucho san cristobal sur", "san cristobal sur santa ana sur", 
                        "sector guaymaral", "conj vivaldi", "caminos san roque", "villa granada", "terranova", 
                        "gratamira etapa", "isierra andes", "mandalay etapa sector ii occidente", "kennedy colombiano villavicencio abastos", "giraldilla", 
                        "versalles occidente", "san vicente ferrer tunjuelito", "paloquemao", "madelena ciudad bolivar", "san jose sur antonio nario", 
                        "tunjuelito tunjuelito", "san antonio noroccidental nororiente", "pepe sierra nororiente", "torre valverde cesar jetta", "salitre greco centro", 
                        "san jose centro", "techo occidente", "california", "castilla castillo", "patio bonito occidente", 
                        "valladolid monerrey kennedy", "chapinero palermo teusaquillo", "crdoba", "san eusebio puente aranda", "sabana martires", 
                        "espanola zaragoza", "multicentro nororiente", "santa ana occidental nororiente", "pradera norte nororiente", "alameda nororiente", 
                        "cedro golf nororiente", "castellana nororiente", "san fernando nororiente", "simon bolivar nororiente", "felicidad pradera", 
                        "baleares", "patio jardin", "ricaurte ricaurte ricaurte", "conejera noroccidente", "aire", 
                        "sector cedro bolivar", "floresta sabana norte", "andalucia kennedy", "rosita", "chico oriental chapinero", 
                        "cedros norte", "ciudad salitre suroriental centro", "lagos cordoba niza noroccidente", "felicidad norte", "pasadena noroccidente", "kenendy central" 
)